# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Graf_wind.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(433, 297)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.tableAlter = QtWidgets.QTableWidget(self.centralwidget)
        self.tableAlter.setObjectName("tableAlter")
        self.tableAlter.setColumnCount(0)
        self.tableAlter.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableAlter)
        self.gridLayout.addLayout(self.verticalLayout_3, 3, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineTarget = QtWidgets.QLineEdit(self.centralwidget)
        self.lineTarget.setObjectName("lineTarget")
        self.verticalLayout.addWidget(self.lineTarget)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 4, 0, 1, 1)
        self.tableKrit = QtWidgets.QTableWidget(self.centralwidget)
        self.tableKrit.setObjectName("tableKrit")
        self.tableKrit.setColumnCount(0)
        self.tableKrit.setRowCount(0)
        self.gridLayout.addWidget(self.tableKrit, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Выбор альтернативы"))
        self.label_2.setText(_translate("MainWindow", "Задайте критерии сравнения"))
        self.label_3.setText(_translate("MainWindow", "Укажите возможные альтернативы"))
        self.label.setText(_translate("MainWindow", "Введите цель выбора"))
        self.pushButton.setText(_translate("MainWindow", "Далее"))
